import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from '@/components/ReduxProvider'
import AuthModal from '@/components/AuthModal'
import { Roboto } from "next/font/google";
import SideBar from "@/components/sidebar/page";
import Search from "@/components/search/page";
import MobileNav from "@/components/mobile-nav/page";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className={`${roboto.className}`}>
        <ReduxProvider>
          <div className="min-h-screen">
          <SideBar />
          <main className="md:ml-50 pb-16 md:pb-0">
          <AuthModal />
          <Search />
          {children}
          </main>
          <MobileNav />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}